name: Run GRDzhadzha Tests (Intel)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      CHOMBO_HOME: ${{ github.workspace }}/Chombo/lib
      OMP_NUM_THREADS: 1
      GRCHOMBO_HOME: ${{ github.workspace }}/GRChombo
      GRCHOMBO_SOURCE: ${{ github.workspace }}/GRChombo/Source

    steps:
    - name: Checkout Chombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/Chombo
        path: Chombo

    - name: Checkout GRChombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/GRChombo
        path: GRChombo

    - name: Checkout GRDzhadzha
      uses: actions/checkout@v2
      with:
        path: GRDzhadzha

    - name: Install Chombo dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install csh libgetopt-complete-perl

    - name: Install Intel compilers
      run: |
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
        | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get -y install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2023.2.4 intel-oneapi-compiler-fortran-2023.2.4 intel-oneapi-mkl-2023.2.0 intel-oneapi-openmp-2023.2.4
      working-directory: /tmp
 
    - name: Instal Intel MPI
      if: matrix.mpi == 'TRUE'
      run: |
        sudo apt-get -y install intel-oneapi-mpi intel-oneapi-mpi-devel 


    - name: Build Chombo
      run: |
        source /opt/intel/oneapi/setvars.sh
        cp $GRCHOMBO_HOME/InstallNotes/MakeDefsLocalExamples/intel-classic-no-hdf5-minimal.Make.defs.local $CHOMBO_HOME/mk/Make.defs.local
        make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools
      working-directory: ${{ env.CHOMBO_HOME }}

    - name: Build GRDzhadzha Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make test -j 4
      working-directory: ${{ github.workspace }}/GRDzhadzha

    - name: Run GRDzhadzha Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make run -j 2
      working-directory: ${{ github.workspace }}/GRDzhadzha
